#!/bin/bash

for d in */ ; do
    cd "$d"
    echo "Updating $d ..."
    dir_name="$(basename "$d")"

    # Generate the commit message
    message="Update \"$dir_name\""

    # Amend the previous commit with the new message
    git commit --amend -m "$message"
    # Push the changes to the remote branch
    git push -f
    # Go back to the repo directory
    cd .. || continue
fi
    cd ..
done

