#!/usr/bin/env bash
# Transfers a file from one server to another using scp
# Accepts four arguments:
#+    path/to/file.
#+    Server IP
#+    Server Username
#+    Path/to/SSH private key

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
