#!/usr/bin/env bash
# Script configures a new Ubuntu Box

echo "Hello World!" | sudo tee /var/www/html/index.html
string_="server_name _;\n\trewrite ^\/redirect_me https\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$string_/" /etc/nginx/sites-enabled/default

sudo service nginx restart
