#!/usr/bin/env bash

# Handles error/redirect to specific pages
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_" /etc/nginx/sites-enabled/default

# restart server
sudo service nginx restart
