#!/usr/bin/env bash
# Configures, and starts the Ha proxy load balancer
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# LB config
DOMAIN_='demoreon.tech'
INIT_='/etc/default/haproxy'
CONF_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONF=\
"
#--$DOMAIN_-params-begin--
backend $DOMAIN_-backend
	balance roundrobin
	option prefer-last-server
	server $hostname 18.209.223.150:80 check
	server $hostname 54.174.240.130:80 check
frontend $DOMAIN_-frontend
	bind *:80
	mode http
	default_backend $DOMAIN_-backend
#--$DOMAIN_-params-end--
"

[ -f "$INIT_" ] || touch "$INIT_"
[ -f "$CONF_FILE" ] || touch "$CONF_FILE"

CONFIGURATION=$(grep -Eco "$DOMAIN_-backend" < $CONF_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_)" -gt 0 ]; then
    sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_"
else
    echo 'ENABLED=1' >> $INIT_
fi

if [ "$CONFIGURATION" -eq 0 ]; then
    echo -e "$HAPROXY_LB_CONF" >> $CONF_FILE
else
    start_="#--$DOMAIN_-params-begin--"
    end_="#--$DOMAIN_-params-end--"
    a=$(grep -onE "$start_" < "$CONf_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sed -i "$a,$b"d "$CONF_FILE"
    echo -en "$HAPROXY_LB_CONF" >> $CONF_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo /etc/init.d/haproxy start
else
    sudo /etc/init.d/haproxy restart
fi
