#!/usr/bin/env bash

# Update and install software properties common
sudo apt-get update
sudo apt-get -y install --no-install-recommends software-properties-common

# Add HAProxy repository and install HAProxy
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get -y install haproxy

# Configure HAProxy
DOMAIN_NAME='demoreon.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
HAPROXY_LB_CONFIG=\
"
#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
        balance roundrobin
	server 141381-web-01 18.209.223.150:80 check
	server 141381-web-02 54.174.240.130:80 check
frontend $DOMAIN_NAME-frontend
	 bind *:80
	 mode http
	 default_backend $DOMAIN_NAME-backend
 #--$DOMAIN_NAME-params-end--
"

# Check if the init script and configuration file exist
[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

# Add the HAProxy configuration to the file
CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < "$CONFIG_FILE")

if [ "$(grep -Eco '^ENABLED=[01]$' < \"$INIT_FILE\")" -gt 0 ]; then
    sudo sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
    echo 'ENABLED=1' | sudo tee -a "$INIT_FILE"
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
    echo -e "$HAPROXY_LB_CONFIG" | sudo tee -a "$CONFIG_FILE"
else
    start_tkn="#--$DOMAIN_NAME-params-begin--"
    end_tkn="#--$DOMAIN_NAME-params-end--"
    a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
    a=$((a - 1))
    b=$((b + 1))
    sudo sed -i "$a,$b"d "$CONFIG_FILE"
    echo -en "$HAPROXY_LB_CONFIG" | sudo tee -a "$CONFIG_FILE"
fi

# Manage the HAProxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
   sudo service haproxy restart
fi
	
