#!/usr/bin/env bash
# Scripts to create and remove file.

rmfile()
{
    rm -f /var/run/myscript.pid;
    exit
}
trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rmfile" SIGTERM
trap "echo 'I hate the kill command'; rmfile" SIGQUIT


echo $$ >> /var/run/myscript.pid
while (true)
do
    echo 'To infinity and beyond'
    sleep 2
done
