#!/usr/bin/env bash
# This script manages my_process

argv1=$1
tmp="/var/run/my_process.pid"

startLoop()
{
    ./manage_my_process &
    echo "$!" > "$tmpfile"
}
killLoop()
{
    #kill "$(cat "$tmp")"
    sudo pkill -f "./manage_my_process"
    rm "$tmp"
}
case "$argv1" in
    start) echo "manage_my_process started"
	startLoop
	;;
    stop) echo "manage_my_process stopped"
	killLoop
	;;
    restart) echo "manage_my_process restarted"
	killLoop
	startLoop
	;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
