#!/usr/bin/env bash
# Prints "Best School" 10 times, "bad luck" the times, and "good luck" the 8th time.
i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( i++ ))
done
