#!/usr/bin/env bash
# Loops through 1 to 20;print "bad luck from China" if a = 4,
# "bad luck from Japan" if a = 9, and "bad luck from Italy" the 17th time
a=1
while [ "$a" -le 20 ]
do
    echo "$a"
    case $a in
	4) echo "bad luck from China" ;;
	9) echo "bad luck from Japan" ;;
	17) echo "bad luck from Italy" ;;
    esac
    (( a++ ))
done
