#!/usr/bin/env bash
# A script to config ufw firewall to block all incoming traffic but 22,443,80

sudo apt update
sudo apt install ufw
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status
